server:
  port: 80

spring:
  application:
#    name: cloud-order-service
     name: consumer-order-service
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机
#      defaultZone: http://localhost:7001/eureka
      #集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    # 服务实例去拉取readOnly缓存的注册表
    registry-fetch-interval-seconds: 3
    healthcheck:
      # 开启健康检查
      enabled: true
  # 服务实例名称
  instance:
#    instance-id: ewp-order
    instance-id: order-instance
    # client发送eureka心跳的间隔时间
    lease-renewal-interval-in-seconds: 3



