server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
     # 服务超过多少秒之后认为挂了
    lease-expiration-duration-in-seconds: 3
  client:
      # false表示不向注册中心注册自己
      register-with-eureka: false
      # false表示自己端就是注册中心,我的职责就是维护服务实例本身,并不需要去检索服务
      fetch-registry: false
      service-url:
        # 设置与Eureka Server交互的地址查询服务和注册服务都需要去依赖这个地址
        # 单机的情况下注册自己
        #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        # 集群的情况下注册到其他的eureka
        defaultZone: http://eureka7001.com:7001/eureka/
  server:
      # 关闭自我保护机制,保证不可用服务被及时剔除
      enable-self-preservation: false
      # 清除无效服务实例的时间
      eviction-interval-timer-in-ms: 2000
      # readOnly和readOrite二级缓存数据表同步时间
      response-cache-update-interval-ms: 3000

