server:
  port: 80

# 服务别名---注册zookeeper到注册中心的名称
spring:
  application:
     name: consumer-order-instance
#    name: cloud-consumer-order-new
  cloud:
    zookeeper:
      connect-string: 192.168.121.150:2181

